module.exports = {
	SUCCESS : 0,
	MISSING_PARAMETERS : 2,
	INTERNAL_SERVER_ERROR : 500,
	USERNAME_EXISTED : 3,
	EMAIL_EXISTED : 4,
	AUTHENTICATE_FAILED: -1,
	FOUND_RELATED_DATA : -9,
	DATA_EXISTED : -5,
	DATA_NOT_FOUND : -4,
    DATABASE_ERROR : -3,
	PARAMETER_ERROR : -2,
	QUICK_CALL_PAUSE : 11,
	QUICK_CALL_ACCEPTED : 9,
	OPERATION_ERROR: -1,
	OPERATION_SUCCESS: 1
};
